### ISSUE TITLE
wsrep_cluster_size is 1

### ISSUE THREAD

**Issue by lizoc** [EgoAleSum/mariadb-cluster#4] opened 2017-04-01 09:11 UTC
I have deployed on azure and set up phpmysql to interact with the load balancer. Logon as root via web portal > console > show global variables, and wsrep_cluster_size is 1 even though there are 3 nodes. Any ideas?

**Comment by ItalyPaleAle** [comment] 2017-04-01 18:32
I am not able to reproduce the issue on a newly-deployed cluster. Things that might be causing this:

- The etcd discovery token is invalid
- The VMs cannot connect to the Internet (making outbound connections)
- Connecting to the wrong server

Could you please try again re-deploying the cluster, making sure that in the "cloud-config" section you see a valid etcd discovery token?

I'm closing the issue for now

**Closed as completed by ItalyPaleAle** 2017-04-01 18:32 UTC

**Comment by imacks** [comment] 2017-04-02 03:39
I can reproduce the issue with my setup. In an existing resource group, I have a vnet in the 172.16.x.0/21 range. Now I run the following arm template to create a new subnet called MariaDB-Subnet in 172.16.(x+4).0/21. I have 3 nodes each with 2x32gb data disks per your config. I run your generator app and copy paste the cloudconfig data.

I created an option to create/attach the data disks. The idea is that I may replicate my data in a cluster 1 to another cluster 2, then delete cluster 1 vms but not the data vhd blobs (i.e delete all resources created by the arm template except the subnet, load balancer and storage accounting -like `*mdbvhd*`). After some time I will do the reverse, recreating the VMs in cluster 1 and attach existing vhd blobs. Then after replication cluster 2 VMs get deleted. The benefit is that I can spread the cost over 2 subscriptions on Azure 🍡 .

When creating cluster 1 for the first time everything goes without a hitch. But now I stop the nodes randomly one by one, until all are stopped. Then I start them one at a time in random order too, until all are running. I tried this a number of times, and sometimes node0 works and the rest don't, while other times the whole thing goes down. SSH into bad nodes and verified that docker ps not starting. Journal in nodes say 'Waiting for initialization..', so port 4001 is in state 503. curl google.com works so nodes have internet access. I suspect that the order of starting up the nodes matter somehow.

The second scenario with me trying to redeploy and attach existing disks actually works, but its a very slow wait. Not sure if it is hogged up on downloading docker image or something else...

Would it be possible to use something other than etcd.io? If we can reserve static private ip in Azure, and node names are fixed, would it be simpler to just test the sql port of other nodes to verify service has started? That way we can remove internet access for the nodes too after deployment.

Here is my arm template adapted from your source.

ps. I choose A1 standard v2 because it costs less with more ram. Don't think that is relevant to the issue but just saying...

````
{
    "$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#",
    "contentVersion": "1.0.0.0",
    "parameters": {
        "facilityNamePrefix": {
            "type": "string",
            "metadata": {
                "description": "Unique name for the facility in this subscription. This is usually the resounce group name with the -RG suffix removed."
            }
        },
        "vmSize": {
            "type": "string",
            "defaultValue": "Standard_A1_v2",
            "metadata": {
                "description": "Instance size for the VMs"
            }
        },
        "vnetIPBaseIndex": {
            "type": "int",
            "allowedValues": [
                0, 8, 16, 24, 32, 40, 48, 56,
                72, 80, 88, 96, 104, 112, 120,
                128, 136, 144, 152, 160, 168,
                176, 184, 192, 200, 208, 216,
                224, 232, 240, 248
            ],
            "metadata": {
                "description": "Third section of the IP address 172.16.x.0/21. Make sure it is not used by other VNets you intend to bridge later."
            }
        },
        "dataDiskSizeGB": {
            "type": "int",
            "defaultValue": 32,
            "minValue": 32,
            "maxValue": 1023,
            "metadata": {
                "description": "Size of each data disk. 2 disks will be created per machine."
            }
        },
        "numberOfNodes": {
            "type": "int",
            "defaultValue": 3,
            "minValue": 3,
            "maxValue": 5,
            "metadata": {
                "description": "Number of nodes to create"
            }
        },
        "adminUserName": {
            "type": "string",
            "defaultValue": "super",
            "metadata": {
                "description": "Username to login to the VMs"
            }
        },
        "createOption": {
            "type": "string",
            "defaultValue": "empty",
            "allowedValues": [ "attach", "empty" ],
            "metadata": {
                "description": "Choose attach if this is a redeployment on existing resource."
            }
        },
        "sshKeyData": {
            "type": "string",
            "metadata": {
                "description": "Public key for SSH authentication"
            }
        },
        "cloudConfig": {
            "type": "string",
            "metadata": {
                "description": "Base64-encoded cloud-config.yaml file"
            }
        }
    },
    "variables": {
        "facilityNamePrefixToLower": "[toLower(parameters('facilityNamePrefix'))]",
        "storageAccountNamePrefix": "[variables('facilityNamePrefixToLower')]",
        "securityGroupName": "MariaDB-NSG",
        "virtualNetworkName": "[concat(parameters('facilityNamePrefix'), '-VNet')]",
        "addressPrefix": "[concat('172.16.', parameters('vnetIPBaseIndex'), '.0/21')]",
        "subnet1Index": "[add(parameters('vnetIPBaseIndex'), 4)]",
        "subnet1Name": "MariaDB-Subnet",
        "subnet1Prefix": "[concat('172.16.', variables('subnet1Index'), '.0/24')]",
        "subnet1Ref": "[concat(resourceId('Microsoft.Network/virtualNetworks', variables('virtualNetworkName')), '/subnets/', variables('subnet1Name'))]",
        "subnet1Id": "[concat('Microsoft.Network/virtualNetworks/', variables('virtualNetworkName'), '/subnets/', variables('subnet1Name'))]",
        "vmNamePrefix": "mariadb-node-",
        "osImageSku": "Stable",
        "nicNamePrefix": "MariaDB-NIC-",
        "availabilitySetName": "MariaDB-AS",
        "vhdStorageAccountName": "[toLower(concat(variables('storageAccountNamePrefix'), 'mdb'))]",
        "vhdStorageAccountType": "Standard_LRS",
        "diagStorageAccountName": "[toLower(concat(variables('storageAccountNamePrefix'), 'mdbdiag'))]",
        "diagStorageAccountType": "Standard_LRS",
        "sshKeyPath": "[concat('/home/', parameters('adminUsername'),'/.ssh/authorized_keys')]",
        "loadBalancerIp": "[concat('172.16.', variables('subnet1Index'), '.4')]",
        "loadBalancerName": "MariaDB-LB",
        "backendPoolName": "BackendPoolMySQL",
        "backendPoolRef": "[concat(resourceId('Microsoft.Network/loadBalancers/', variables('loadBalancerName')), '/backendAddressPools/', variables('backendPoolName'))]",
        "lbRef": "[resourceId('Microsoft.Network/loadBalancers', variables('loadBalancerName'))]",
        "lbRuleName": "MySQL-Rule",
        "lbProbeName": "MySQL-Probe"
    },
    "resources": [
        {
            "apiVersion": "2015-06-15",
            "type": "Microsoft.Storage/storageAccounts",
            "name": "[variables('vhdStorageAccountName')]",
            "location": "[resourceGroup().location]",
            "properties": {
                "accountType": "[variables('vhdStorageAccountType')]"
            }
        },
        {
            "apiVersion": "2015-06-15",
            "type": "Microsoft.Storage/storageAccounts",
            "name": "[variables('diagStorageAccountName')]",
            "location": "[resourceGroup().location]",
            "properties": {
                "accountType": "[variables('diagStorageAccountType')]"
            }
        },
        {
            "apiVersion": "2015-06-15",
            "type": "Microsoft.Network/networkSecurityGroups",
            "name": "[variables('securityGroupName')]",
            "location": "[resourceGroup().location]",
            "properties": {
                "securityRules": [
                    {
                        "name": "Allow-SSH-Lan",
                        "properties": {
                            "description": "Allows SSH traffic from the Virtual Network",
                            "protocol": "Tcp",
                            "sourcePortRange": "*",
                            "sourceAddressPrefix": "VirtualNetwork",
                            "destinationPortRange": "22",
                            "destinationAddressPrefix": "*",
                            "access": "Allow",
                            "priority": 100,
                            "direction": "Inbound"
                        }
                    },
                    {
                        "name": "Allow-MySQL-Lan",
                        "properties": {
                            "description": "Allows MySQL traffic from the Virtual Network",
                            "protocol": "Tcp",
                            "sourcePortRange": "*",
                            "sourceAddressPrefix": "VirtualNetwork",
                            "destinationPortRange": "3306",
                            "destinationAddressPrefix": "*",
                            "access": "Allow",
                            "priority": 200,
                            "direction": "Inbound"
                        }
                    },
                    {
                        "name": "Allow-MDB-Replication-Subnet",
                        "properties": {
                            "protocol": "UDP",
                            "sourcePortRange": "*",
                            "destinationPortRange": "4567",
                            "sourceAddressPrefix": "[concat('172.16.', variables('subnet1Index'), '.0/24')]",
                            "destinationAddressPrefix": "*",
                            "access": "Allow",
                            "priority": 210,
                            "direction": "Inbound"
                        }
                    },
                    {
                        "name": "Allow-MDB-Replication2-Subnet",
                        "properties": {
                            "protocol": "TCP",
                            "sourcePortRange": "*",
                            "destinationPortRange": "4567-4568",
                            "sourceAddressPrefix": "[concat('172.16.', variables('subnet1Index'), '.0/24')]",
                            "destinationAddressPrefix": "*",
                            "access": "Allow",
                            "priority": 220,
                            "direction": "Inbound"
                        }
                    },
                    {
                        "name": "Allow-MDB-Replication3-Subnet",
                        "properties": {
                            "protocol": "TCP",
                            "sourcePortRange": "*",
                            "destinationPortRange": "4444",
                            "sourceAddressPrefix": "[concat('172.16.', variables('subnet1Index'), '.0/24')]",
                            "destinationAddressPrefix": "*",
                            "access": "Allow",
                            "priority": 230,
                            "direction": "Inbound"
                        }
                    },
                    {
                        "name": "Allow-ETCD2-Discovery-Subnet",
                        "properties": {
                            "protocol": "TCP",
                            "sourcePortRange": "*",
                            "destinationPortRange": "2380",
                            "sourceAddressPrefix": "[concat('172.16.', variables('subnet1Index'), '.0/24')]",
                            "destinationAddressPrefix": "*",
                            "access": "Allow",
                            "priority": 240,
                            "direction": "Inbound"
                        }
                    }
                ]
            }
        },
        {
            "apiVersion": "2015-06-15",
            "type": "Microsoft.Network/virtualNetworks/subnets",
            "name": "[concat(variables('virtualNetworkName'), '/', variables('subnet1Name'))]",
            "location": "[resourceGroup().location]",
            "properties": {
                "addressPrefix": "[variables('subnet1Prefix')]"
            }
        },
        {
            "apiVersion": "2015-06-15",
            "type": "Microsoft.Network/networkInterfaces",
            "name": "[concat(variables('nicNamePrefix'), copyindex())]",
            "copy": {
                "name": "nicLoop",
                "count": "[parameters('numberOfNodes')]"
            },
            "location": "[resourceGroup().location]",
            "dependsOn": [
                "[concat('Microsoft.Network/loadBalancers/', variables('loadBalancerName'))]",
                "[concat('Microsoft.Network/networkSecurityGroups/', variables('securityGroupName'))]",
                "[variables('subnet1Id')]"
            ],
            "properties": {
                "ipConfigurations": [
                    {
                        "name": "defaultIPConfig",
                        "properties": {
                            "privateIPAllocationMethod": "Static",
                            "privateIPAddress": "[concat('172.16.', variables('subnet1Index'), '.', add(copyIndex(), 5))]",
                            "subnet": {
                                "id": "[variables('subnet1Ref')]"
                            },
                            "loadBalancerBackendAddressPools": [
                                {
                                    "id": "[variables('backendPoolRef')]"
                                }
                            ]
                        }
                    }
                ],
                "networkSecurityGroup": {
                    "id": "[resourceId('Microsoft.Network/networkSecurityGroups', variables('securityGroupName'))]"
                }
            }
        },
        {
            "apiVersion": "2015-06-15",
            "type": "Microsoft.Compute/availabilitySets",
            "name": "[variables('availabilitySetName')]",
            "location": "[resourceGroup().location]"
        },
        {
            "apiVersion": "2015-06-15",
            "type": "Microsoft.Network/loadBalancers",
            "name": "[variables('loadBalancerName')]",
            "location": "[resourceGroup().location]",
            "dependsOn": [
                "[variables('subnet1Id')]"
            ],
            "properties": {
                "frontendIPConfigurations": [
                    {
                        "name": "LoadBalancerFrontend",
                        "properties": {
                            "subnet": {
                                "id": "[variables('subnet1Ref')]"
                            },
                            "privateIPAddress": "[variables('loadBalancerIp')]",
                            "privateIPAllocationMethod": "Static"
                        }
                    }
                ],
                "backendAddressPools": [
                    {
                        "name": "[variables('backendPoolName')]"
                    }
                ],
                "loadBalancingRules": [
                    {
                        "name": "[variables('lbRuleName')]",
                        "properties": {
                            "frontendIPConfiguration": {
                                "id": "[concat(variables('lbRef'), '/frontendIpConfigurations/LoadBalancerFrontend')]"
                            },
                            "backendAddressPool": {
                                "id": "[concat(variables('lbRef'), '/backendAddressPools/', variables('backendPoolName'))]"
                            },
                            "probe": {
                                "id": "[concat(variables('lbRef'), '/probes/', variables('lbProbeName'))]"
                            },
                            "protocol": "Tcp",
                            "frontendPort": 3306,
                            "backendPort": 3306,
                            "idleTimeoutInMinutes": 15
                        }
                    }
                ],
                "probes": [
                    {
                        "name": "[variables('lbProbeName')]",
                        "properties": {
                            "protocol": "Tcp",
                            "port": 3306,
                            "intervalInSeconds": 15,
                            "numberOfProbes": 2
                        }
                    }
                ]
            }
        },
        {
            "apiVersion": "2015-06-15",
            "type": "Microsoft.Compute/virtualMachines",
            "name": "[concat(variables('vmNamePrefix'), copyindex())]",
            "copy": {
                "name": "vmLoop",
                "count": "[parameters('numberOfNodes')]"
            },
            "location": "[resourceGroup().location]",
            "dependsOn": [
                "[concat('Microsoft.Storage/storageAccounts/', variables('vhdStorageAccountName'))]",
                "[concat('Microsoft.Storage/storageAccounts/', variables('diagStorageAccountName'))]",
                "[concat('Microsoft.Compute/availabilitySets/', variables('availabilitySetName'))]",
                "[concat('Microsoft.Network/networkInterfaces/', variables('nicNamePrefix'), copyindex())]",
                "[concat('Microsoft.Storage/storageAccounts/', toLower(concat(variables('storageAccountNamePrefix'), 'mdbvhd', copyindex())))]"
            ],
            "properties": {
                "availabilitySet": {
                    "id": "[resourceId('Microsoft.Compute/availabilitySets', variables('availabilitySetName'))]"
                },
                "hardwareProfile": {
                    "vmSize": "[parameters('vmSize')]"
                },
                "osProfile": {
                    "computerName": "[concat(variables('vmNamePrefix'), copyindex())]",
                    "adminUsername": "[parameters('adminUsername')]",
                    "customData": "[parameters('cloudConfig')]",
                    "linuxConfiguration": {
                        "disablePasswordAuthentication": "true",
                        "ssh": {
                            "publicKeys": [
                                {
                                    "path": "[variables('sshKeyPath')]",
                                    "keyData": "[parameters('sshKeyData')]"
                                }
                            ]
                        }
                    }
                },
                "storageProfile": {
                    "imageReference": {
                        "publisher": "CoreOS",
                        "offer": "CoreOS",
                        "sku": "[variables('osImageSku')]",
                        "version": "latest"
                    },
                    "osDisk": {
                        "name": "[concat(variables('vmNamePrefix'), copyindex())]",
                        "vhd": {
                            "uri": "[concat('http://', variables('vhdStorageAccountName'), '.blob.core.windows.net/vhds/', variables('vmNamePrefix'), copyindex(),'-OS', '.vhd')]"
                        },
                        "caching": "ReadWrite",
                        "createOption": "FromImage"
                    },
                    "dataDisks": [
                        {
                            "name": "DataDisk0",
                            "diskSizeGB": "[parameters('dataDiskSizeGB')]",
                            "lun": 0,
                            "vhd": {
                                "uri": "[concat('http://', toLower(concat(variables('storageAccountNamePrefix'), 'mdbvhd', copyindex())), '.blob.core.windows.net/vhds/', variables('vmNamePrefix'), copyindex(), '-DataDisk0', '.vhd')]"
                            },
                            "caching": "None",
                            "createOption": "[parameters('createOption')]"
                        },
                        {
                            "name": "DataDisk1",
                            "diskSizeGB": "[parameters('dataDiskSizeGB')]",
                            "lun": 1,
                            "vhd": {
                                "uri": "[concat('http://', toLower(concat(variables('storageAccountNamePrefix'), 'mdbvhd', copyindex())), '.blob.core.windows.net/vhds/', variables('vmNamePrefix'), copyindex(), '-DataDisk1', '.vhd')]"
                            },
                            "caching": "None",
                            "createOption": "[parameters('createOption')]"
                        }
                    ]
                },
                "networkProfile": {
                    "networkInterfaces": [
                        {
                            "id": "[resourceId('Microsoft.Network/networkInterfaces', concat(variables('nicNamePrefix'), copyindex()))]"
                        }
                    ]
                },
                "diagnosticsProfile": {
                    "bootDiagnostics": {
                        "enabled": "true",
                        "storageUri": "[concat('http://', variables('diagStorageAccountName'), '.blob.core.windows.net')]"
                    }
                }
            }
        },
        {
            "apiVersion": "2015-06-15",
            "type": "Microsoft.Storage/storageAccounts",
            "name": "[toLower(concat(variables('storageAccountNamePrefix'), 'mdbvhd', copyindex()))]",
            "copy": {
                "name": "storageLoop",
                "count": "[parameters('numberOfNodes')]"
            },
            "location": "[resourceGroup().location]",
            "properties": {
                "accountType": "[variables('vhdStorageAccountType')]"
            }
        }
    ]
}

````

**Comment by ItalyPaleAle** [comment] 2017-04-02 17:08
Hi @imacks 

This:

> But now I stop the nodes randomly one by one, until all are stopped.

Is the issue. Galera clusters are not meant to be shut down completely, and you need to ensure that you always have at least 1 node running. If all nodes are shut down, you need to re-bootstrap the cluster again, as per here: http://galeracluster.com/documentation-webpages/restartingcluster.html

Please note that this project is a community effort, and neither myself nor Microsoft are able to provide support with custom configurations.

On a side note, however, if your goal is to leverage multiple subscriptions (I assume it's because you want more Azure credits from MSDN etc?), you might want to change your strategy. I'd suggest creating a cluster that "stretches" across multiple VNets (in multiple subscriptions), all peered using [VNet Peering](https://docs.microsoft.com/en-us/azure/virtual-network/virtual-network-peering-overview)
