### ISSUE TITLE
docker-mariadb-galera.service - stop command fails

### ISSUE THREAD

**Issue by haraldkoch** [EgoAleSum/mariadb-cluster#3] opened 2017-03-08 23:50 UTC
When I run `sudo systemctl stop docker-mariadb-galera` I get an error:

```
Mar 08 23:51:48 cluster1 systemd[1]: Stopping MariaDB with Galera Cluster...
Mar 08 23:51:48 cluster1 bash[23455]: Error response from daemon: No such container: mariadb-container-

```

This appears to be because in the `ExecStop` command that parses out a value for `HOSTNUM`, the variable substitution (with an empty value) happens before the parsing actually occurs.

The container still gets stopped on my machine; I think the `ExecStop` command probably isn't necessary at all. The docker command inside `docker-mariadb-galera.sh` runs in the foreground (no `-d` argument), so systemd is able to send it signals, and that causes docker to shut down the container.

**Comment by ItalyPaleAle** [comment] 2017-04-01 18:38
Hi @haraldkoch sorry for the delay in responding.

I cannot reproduce the issue when running the VMs on Azure. Are you using the ARM template for Azure, or are you just using the cloud-config? What distribution are you using - CoreOS?

If you're not using the ARM templates for Azure, please make sure you review the notes here: https://github.com/EgoAleSum/mariadb-cluster#using-the-cloud-config-mode
The hostnames of the VMs must be `mariadb-node-0` until `mariadb-node-4`.

Closing for now.

**Closed as completed by ItalyPaleAle** 2017-04-01 18:38 UTC
